### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kittenvr** [RattlesHyper/TrafficerMC#54] opened 2023-08-13 21:30 UTC
there is a bug you cant stop it when starting it

**Comment by wendellmeset** [comment] 2023-08-16 22:52
Yes you can, please provide more info or close the issue. Or EXACT STEPS to reproduce the problem.

**Comment by kittenvr** [comment] 2023-08-16 22:55
> Yes you can, please provide more info or close the issue. Or EXACT STEPS to reproduce the problem.

Click start and spam stop

**Comment by kittenvr** [comment] 2023-08-17 13:39
> > Yes you can, please provide more info or close the issue. Or EXACT STEPS to reproduce the problem.
> 
> Click start and spam stop

with like 100 bots

**Comment by RattlesHyper** [comment] 2023-08-22 16:35
[STOP] stops sending more bots, if the bots are delayed because of internet they will still try to connect.

**Closed by RattlesHyper** 2023-08-22 16:35 UTC
